defaults:
  - gateway: mock
  - store: redis
  - _self_

env: "dev"
symbol: "BTC/USDT"
symbols:
  - "BTC/USDT"
  - "ETH/USDT"
  - "SOL/USDT"
  - "XRP/USDT"

oms:
  initial_cash: 100000.0
  risk_fraction: 0.04
  account_mode: "margin"
  short_leverage: 1.0

agents:
  strategies:
    - _target_: qts_core.agents.base.TechnicalAgent
      name: TrendFollower_A
      bullish_threshold: 0.002
    - _target_: qts_core.agents.base.TechnicalAgent
      name: MeanReversion_B
      bullish_threshold: 0.002
    - _target_: qts_core.agents.ict.ICTSmartMoneyAgent
      name: ICT_Sniper_NY
      symbol: BTC/USDT
      session_start: 0
      session_end: 24
  risk:
    _target_: qts_core.agents.base.StrictRiskAgent
    name: GlobalRiskOfficer

loop:
  tick_interval: 10.0
  heartbeat_key: "SYSTEM:HEARTBEAT"
  execution_timeout: 20.0
  max_session_drawdown: 0.10
  entry_cooldown_seconds: 90.0
  max_entries_per_candle_per_symbol: 1

execution_guardrails:
  enabled: true
  min_volume: 0.10
  max_intrabar_volatility: 0.05
  high_volatility_size_scale: 0.40
  max_estimated_slippage_bps: 30.0
  slippage_volatility_factor: 0.25

trading:
  timeframe: "1h"

alerts:
  enabled: true
  last_key: "ALERTS:LAST"
  event_prefix: "ALERTS:EVENT"

telemetry:
  publish_views: true
  metrics_keys:
    total_value: "METRICS:TOTAL_VALUE"
    cash: "METRICS:CASH"
    pnl_daily: "METRICS:PNL_DAILY"
  latency_keys:
    tick_to_decision_ms: "METRICS:LATENCY:TICK_TO_DECISION_MS"
    decision_to_fill_ms: "METRICS:LATENCY:DECISION_TO_FILL_MS"
    tick_to_fill_ms: "METRICS:LATENCY:TICK_TO_FILL_MS"
  orders_key: "VIEW:ORDERS"
  positions_key: "VIEW:POSITIONS"
  last_price_key: "MARKET:LAST_PRICE"
  last_tick_key: "MARKET:LAST_TICK"
  ohlcv_key: "MARKET:OHLCV"
