_target_: qts_core.execution.ems.CCXTGateway
exchange_name: "kraken"
sandbox: false
apiKey: "${oc.env:KRAKEN_API_KEY,}"
secret: "${oc.env:KRAKEN_API_SECRET,}"
paper_trading: true
account_mode: "margin"
